// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Api_Farmacia.Controllers.DTO_s.Medicamento;
using System;
using System.Collections.Generic;

namespace Api_Farmacia.Models;

public partial class Medicamento
{
    public int Id { get; set; }

    public bool Estado { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<DetalleFactura> DetallesFacturas { get; set; } = new List<DetalleFactura>();
}